version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Building Java project...
      - mvn clean package  # or `mvn clean install` if you prefer

artifacts:
  files:
    - target/*.jar  # or whatever the final JAR name is

